[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }
fs_permissions = [{ access = "read", path = "./" }]
solc_args = ["--ignore-warnings"]


[rpc_endpoints]
local = "http://localhost:8545"
rootstock = "https://31.rpc.thirdweb.com"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/EB1X00XXCX8XWFRB7OR-uKwhkij6NNfE"

[etherscan]
rootstock = { key = "TUCDN8F9GJBGD7K9MKVFT8TV7ZR4XRQIC3", url = "https://rootstock-testnet.blockscout.com" }
sepolia = { key = "TUCDN8F9GJBGD7K9MKVFT8TV7ZR4XRQIC3", url = "https://api-sepolia.etherscan.io/api" }